version: '3.8'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: A936522#a
      MYSQL_DATABASE: TransactionDb
      MYSQL_PASSWORD: A936522#a
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: expensetrackerapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      ASPNETCORE_ENVIRONMENT : Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=TransactionDb;Uid=root;Pwd=A936522#a;"

volumes:
  mysql_data:
